spring.application.name=aclub

# db connection
spring.datasource.url=jdbc:h2:mem:aclub
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.path=/h2-console
spring.h2.console.enabled=true

# microsoft oauth
spring.security.oauth2.client.registration.microsoft.client-id=bfa7621c-9c2e-4dbc-a367-c5c578c936bb
spring.security.oauth2.client.registration.microsoft.client-secret=~hw8Q~ve..ZceB.ZQaZsm5CiGv6L2ZLtS2GmBc~2
spring.security.oauth2.client.registration.microsoft.scope=openid,email,profile
spring.security.oauth2.client.registration.microsoft.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.microsoft.redirect-uri=http://localhost:8080/login/oauth2/code/microsoft
spring.security.oauth2.client.provider.microsoft.authorization-uri=https://login.microsoftonline.com/7359f896-71e2-4dae-b8a3-15cdf97f2f10/oauth2/v2.0/authorize
spring.security.oauth2.client.provider.microsoft.token-uri=https://login.microsoftonline.com/7359f896-71e2-4dae-b8a3-15cdf97f2f10/oauth2/v2.0/token
spring.security.oauth2.client.provider.microsoft.jwk-set-uri=https://login.microsoftonline.com/7359f896-71e2-4dae-b8a3-15cdf97f2f10/discovery/v2.0/keys
spring.security.oauth2.client.provider.microsoft.user-info-uri=https://graph.microsoft.com/oidc/userinfo
spring.security.oauth2.client.provider.microsoft.user-name-attribute=sub

# for debugging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=TRACE

# For email sending
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=prudvisatyateja123@gmail.com
spring.mail.password=atgswrqrdberunqi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# for usage
app.frontend.url=http://localhost:5173
app.jwt.access-token-expiry=5
app.jwt.refresh-token-expiry=15
app.cookie.secure=false
app.cookie.refresh-path=/refresh-token