name: Keep Render Awake

on:
  schedule:
    - cron: "*/14 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Spring Boot Backend
        run: curl -I https://aclub-campus.onrender.com/api/health